import 'bootstrap/dist/css/bootstrap.css';
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{
        background : "linear-gradient(135deg, #000000, #003366)", width : "100vw", height : "100vh",
      }}>
      {children}
      </body>
    </html>
  );
}
